In [1]:
pip install huggingface_hub

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
huggingface-cli login

SyntaxError: invalid syntax (1355118443.py, line 1)

In [3]:
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 login


SyntaxError: invalid syntax (3331430585.py, line 1)

In [4]:
pip install transformers


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [5]:
python -c "from transformers import pipeline; print(pipeline('sentiment-analysis')('we love you'))"


SyntaxError: invalid syntax (4063614406.py, line 1)

In [6]:
pip install -U sentence-transformers


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [9]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')


OSError: Unable to load weights from pytorch checkpoint file for 'C:\Users\ASUS/.cache\torch\sentence_transformers\sentence-transformers_paraphrase-MiniLM-L6-v2\pytorch_model.bin' at 'C:\Users\ASUS/.cache\torch\sentence_transformers\sentence-transformers_paraphrase-MiniLM-L6-v2\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

In [10]:
sentence = ['This framework generates embeddings for each input sentence']



In [11]:
embedding = model.encode(sentence)



NameError: name 'model' is not defined

In [12]:
!pip install -U sentence-transformers


Defaulting to user installation because normal site-packages is not writeable


In [13]:
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')


In [14]:
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.']


embeddings = model.encode(sentences)


In [15]:
embeddings


array([[-1.37173459e-02, -4.28515263e-02, -1.56286247e-02,
         1.40537536e-02,  3.95537727e-02,  1.21796325e-01,
         2.94333640e-02, -3.17523852e-02,  3.54959480e-02,
        -7.93139860e-02,  1.75878443e-02, -4.04369384e-02,
         4.97259498e-02,  2.54912544e-02, -7.18700439e-02,
         8.14968571e-02,  1.47069583e-03,  4.79627103e-02,
        -4.50336039e-02, -9.92175341e-02, -2.81769466e-02,
         6.45046085e-02,  4.44670431e-02, -4.76216935e-02,
        -3.52952629e-02,  4.38671745e-02, -5.28565943e-02,
         4.33011563e-04,  1.01921491e-01,  1.64072290e-02,
         3.26996557e-02, -3.45986746e-02,  1.21339597e-02,
         7.94871002e-02,  4.58340580e-03,  1.57778189e-02,
        -9.68208816e-03,  2.87625697e-02, -5.05805984e-02,
        -1.55793950e-02, -2.87906844e-02, -9.62282252e-03,
         3.15556303e-02,  2.27348972e-02,  8.71449485e-02,
        -3.85027491e-02, -8.84718448e-02, -8.75498727e-03,
        -2.12343019e-02,  2.08923742e-02, -9.02077705e-0

In [16]:
import pandas as pd 

In [17]:
df=pd.read_csv('Desktop/flipkart_com-ecommerce_sample oredr 4 - flipkart_com-ecommerce_sample oredr 2 - flipkart_com-ecommerce_sample.csv')
df.head()
df.columns

Index(['uniq_id', 'crawl_timestamp', 'product_url', 'product_name',
       'product_category_tree', 'pid', 'retail_price', 'discounted_price',
       'image', 'is_FK_Advantage_product', 'description', 'product_rating',
       'overall_rating', 'brand', 'product_specifications'],
      dtype='object')

In [18]:
df

uniq_id            crawl_timestamp  \
0      c2d766ca982eca8304150849735ffef9  2016-03-25 22:59:23 +0000   
1      f449ec65dcbc041b6ae5e6a32717d01b  2016-03-25 22:59:23 +0000   
2      0973b37acd0c664e3de26e97e5571454  2016-03-25 22:59:23 +0000   
3      bc940ea42ee6bef5ac7cea3fb5cfbee7  2016-03-25 22:59:23 +0000   
4      c2a17313954882c1dba461863e98adf2  2016-03-25 22:59:23 +0000   
...                                 ...                        ...   
19974  7179d2f6c4ad50a17d014ca1d2815156  2015-12-01 10:15:43 +0000   
19975  71ac419198359d37b8fe5e3fffdfee09  2015-12-01 10:15:43 +0000   
19976  93e9d343837400ce0d7980874ece471c  2015-12-01 10:15:43 +0000   
19977  669e79b8fa5d9ae020841c0c97d5e935  2015-12-01 10:15:43 +0000   
19978  cb4fa87a874f715fff567f7b7b3be79c  2015-12-01 10:15:43 +0000   

                                             product_url  \
0      http://www.flipkart.com/alisha-solid-women-s-c...   
1      http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
2      http://www.flipkart.com/alisha-solid-women-s-c...   
3      http://www.flipkart.com/sicons-all-purpose-arn...   
4      http://www.flipkart.com/eternal-gandhi-super-s...   
...                                                  ...   
19974  http://www.flipkart.com/walldesign-small-vinyl...   
19975  http://www.flipkart.com/wallmantra-large-vinyl...   
19976  http://www.flipkart.com/elite-collection-mediu...   
19977  http://www.flipkart.com/elite-collection-mediu...   
19978  http://www.flipkart.com/elite-collection-mediu...   

                                            product_name  \
0                     Alisha Solid Womens Cycling Shorts   
1                                             AW Bellies   
2                     Alisha Solid Womens Cycling Shorts   
3                  Sicons All Purpose Arnica Dog Shampoo   
4      Eternal Gandhi Super Series Crystal Paper Weig...   
...                                                  ...   
19974                     WallDesign Small Vinyl Sticker   
19975            Wallmantra Large Vinyl Stickers Sticker   
19976            Elite Collection Medium Acrylic Sticker   
19977            Elite Collection Medium Acrylic Sticker   
19978            Elite Collection Medium Acrylic Sticker   

                                   product_category_tree               pid  \
0      Clothing , Women's Clothing , Lingerie, Sleep ...  SRTEH2FF9KEDEFGF   
1      Footwear , Women's Footwear , Ballerinas , AW ...  SHOEH4GRSUBJGZXE   
2      Clothing , Women's Clothing , Lingerie, Sleep ...  SRTEH2F6HUZMQ6SJ   
3      Pet Supplies , Grooming , Skin & Coat Care , S...  PSOEH3ZYDMSYARJ5   
4      Eternal Gandhi Super Series Crystal Paper Weig...  PWTEB7H2E4KCYUE3   
...                                                  ...               ...   
19974  Baby Care , Baby & Kids Gifts , Stickers , Wal...  STIE7KFJAKSTDY9G   
19975  Baby Care , Baby & Kids Gifts , Stickers , Wal...  STIE9F5URNQGJCGH   
19976  Baby Care , Baby & Kids Gifts , Stickers , Eli...  STIE7VAYDKQZEBSD   
19977  Baby Care , Baby & Kids Gifts , Stickers , Eli...  STIE8YSVEPPCZ42Y   
19978  Baby Care , Baby & Kids Gifts , Stickers , Eli...  STIE88KN9ZDSGZKY   

       retail_price  discounted_price  \
0             999.0             379.0   
1             999.0             499.0   
2             699.0             267.0   
3             220.0             210.0   
4             430.0             430.0   
...             ...               ...   
19974        1500.0             730.0   
19975        1429.0            1143.0   
19976        1299.0             999.0   
19977        1499.0            1199.0   
19978        1499.0             999.0   

                                                   image  \
0      http://img5a.flixcart.com/image/short/u/4/a/al...   
1      http://img5a.flixcart.com/image/shoe/7/z/z/red...   
2      http://img5a.flixcart.com/image/short/6/2/h/al...   
3      http://img5a.flixcart.com/image/pet-shampoo/r/...   
4      http://img5a

In [19]:
sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.'
          ]


In [20]:
embeddings = model.encode(sentences)


In [21]:
cos_sim = util.cos_sim(embeddings, embeddings)


In [22]:
embeddings


array([[ 0.03324158,  0.00440608, -0.00627695, ...,  0.06917302,
        -0.02458484, -0.03756437],
       [ 0.05251841,  0.05524131, -0.01118819, ..., -0.01619392,
        -0.060229  , -0.04115056],
       [-0.03630896, -0.03565352, -0.02722262, ..., -0.03858706,
         0.10574475, -0.0013147 ],
       ...,
       [ 0.0369864 ,  0.02263786,  0.04961048, ..., -0.00306216,
         0.04889759,  0.01671035],
       [ 0.0234649 , -0.05852915,  0.05599174, ...,  0.05835002,
         0.03770513,  0.04097464],
       [-0.03571462,  0.01683479,  0.04483476, ...,  0.02489525,
         0.06529628, -0.01124186]], dtype=float32)

In [60]:
query=['women clothes']

In [61]:
decode= model.encode(query)

In [62]:
decode

array([[-3.58241946e-02, -3.85088027e-02, -3.54351755e-03,
         6.07362427e-02,  3.53093296e-02,  2.17627478e-03,
         2.90199444e-02, -4.22293879e-02, -6.55196011e-02,
         2.39946544e-02,  5.54445013e-02, -4.76816334e-02,
         2.03532609e-03, -4.89127859e-02, -1.50467129e-03,
         5.12569956e-02,  1.86064839e-02,  5.28438091e-02,
        -2.77511533e-02,  1.08055091e-02, -2.58526411e-02,
        -6.45891652e-02,  1.56977698e-02,  2.17712037e-02,
        -9.47134104e-03,  6.92316738e-04, -5.07730991e-02,
         2.98561323e-02, -7.20624402e-02, -4.11205366e-02,
        -3.80835123e-02,  1.50930118e-02,  3.77844200e-02,
         4.74546775e-02, -6.06286563e-02,  1.31962709e-02,
         4.85722795e-02, -3.59151512e-02,  2.14303825e-02,
         7.80830905e-02, -4.42945398e-02, -8.80315453e-02,
        -5.55099696e-02, -6.80055097e-02,  6.29979447e-02,
         3.52800786e-02,  4.65647355e-02,  1.33575320e-01,
        -9.31281894e-02,  8.68659187e-03,  8.57041106e-0

In [63]:
cos_sim = util.cos_sim(decode, embeddings)


In [64]:
cos_sim


tensor([[0.5119, 0.1782, 0.5119,  ..., 0.1795, 0.1795, 0.1795]])

In [29]:
sort(cos_sim)

NameError: name 'sort' is not defined

In [30]:
sorted(cos_sim)

[tensor([-0.0559, -0.0196, -0.0026,  0.5229, -0.0363,  0.1013,  0.4512, -0.0422,
          0.0367])]

In [31]:
texts=df['product_name'].values.tolist()

In [32]:
texts

['Alisha Solid Womens Cycling Shorts',
 'AW Bellies',
 'Alisha Solid Womens Cycling Shorts',
 'Sicons All Purpose Arnica Dog Shampoo',
 'Eternal Gandhi Super Series Crystal Paper Weights  with Silver Finish',
 'Alisha Solid Womens Cycling Shorts',
 'FabHomeDecor Fabric Double Sofa Bed',
 'dilli bazaaar Bellies Corporate Casuals Casuals',
 'Alisha Solid Womens Cycling Shorts',
 'Ladela Bellies',
 'Carrel Printed Womens',
 'Sicons All Purpose Tea Tree Dog Shampoo',
 'Alisha Solid Womens Cycling Shorts',
 'Freelance Vacuum Bottles 350 ml Bottle',
 'Alisha Solid Womens Cycling Shorts',
 'FabHomeDecor Fabric Double Sofa Bed',
 'Style Foot Bellies',
 'Carrel Printed Womens',
 'FabHomeDecor Fabric Double Sofa Bed',
 'Sicons Conditioning Conditoner Dog Shampoo',
 'Alisha Solid Womens Cycling Shorts',
 'dongli Printed Boys Round Neck T-Shirt',
 'SWAGGA Women Clogs',
 'Kennel Rubber Dumbell With Bell - Small Rubber Rubber Toy For Dog',
 'Glus Wedding Lingerie Set',
 'Veelys Shiny White Quad Roll

In [35]:
import numpy as np

In [36]:
texts = np.array(texts)

In [37]:
texts

array(['Alisha Solid Womens Cycling Shorts', 'AW Bellies',
       'Alisha Solid Womens Cycling Shorts', ...,
       'Elite Collection Medium Acrylic Sticker',
       'Elite Collection Medium Acrylic Sticker',
       'Elite Collection Medium Acrylic Sticker'], dtype='<U287')

In [215]:
texts=df['product_name'].values.tolist()

In [216]:
texts

['Alisha Solid Womens Cycling Shorts',
 'AW Bellies',
 'Alisha Solid Womens Cycling Shorts',
 'Sicons All Purpose Arnica Dog Shampoo',
 'Eternal Gandhi Super Series Crystal Paper Weights  with Silver Finish',
 'Alisha Solid Womens Cycling Shorts',
 'FabHomeDecor Fabric Double Sofa Bed',
 'dilli bazaaar Bellies Corporate Casuals Casuals',
 'Alisha Solid Womens Cycling Shorts',
 'Ladela Bellies',
 'Carrel Printed Womens',
 'Sicons All Purpose Tea Tree Dog Shampoo',
 'Alisha Solid Womens Cycling Shorts',
 'Freelance Vacuum Bottles 350 ml Bottle',
 'Alisha Solid Womens Cycling Shorts',
 'FabHomeDecor Fabric Double Sofa Bed',
 'Style Foot Bellies',
 'Carrel Printed Womens',
 'FabHomeDecor Fabric Double Sofa Bed',
 'Sicons Conditioning Conditoner Dog Shampoo',
 'Alisha Solid Womens Cycling Shorts',
 'dongli Printed Boys Round Neck T-Shirt',
 'SWAGGA Women Clogs',
 'Kennel Rubber Dumbell With Bell - Small Rubber Rubber Toy For Dog',
 'Glus Wedding Lingerie Set',
 'Veelys Shiny White Quad Roll

In [40]:
embeddings = model.encode(texts)


In [41]:
embeddings

array([[-0.02152489,  0.02040687, -0.01363811, ..., -0.0853805 ,
        -0.00751618,  0.00986434],
       [-0.00924347, -0.02759435,  0.02635411, ..., -0.06183816,
        -0.02304253, -0.09012467],
       [-0.02152488,  0.02040688, -0.01363809, ..., -0.08538051,
        -0.00751615,  0.00986434],
       ...,
       [-0.13613081,  0.08268632, -0.05475329, ..., -0.00527374,
        -0.04814892,  0.13334544],
       [-0.13613078,  0.08268633, -0.05475329, ..., -0.00527377,
        -0.0481489 ,  0.13334544],
       [-0.13613075,  0.08268634, -0.05475329, ..., -0.00527374,
        -0.04814892,  0.13334544]], dtype=float32)

In [42]:
size(embeddings)

NameError: name 'size' is not defined

In [43]:
len(embeddings)

19979

In [44]:
embeddings[0]

array([-2.15248894e-02,  2.04068702e-02, -1.36381052e-02,  4.00199331e-02,
        2.15520412e-02,  3.35479490e-02,  6.49650395e-02, -1.25136096e-02,
       -2.40224320e-02, -7.24548241e-04,  1.83947720e-02, -6.50428310e-02,
        9.42037180e-02, -5.65627739e-02,  1.62386615e-02,  8.12329911e-03,
        4.54570837e-02, -2.56171748e-02,  1.16319694e-02,  8.96832421e-02,
       -2.07742359e-02, -5.53828217e-02,  5.55749830e-05,  1.06912903e-01,
       -4.29349132e-02, -8.54887161e-03,  6.48122877e-02, -9.22919251e-03,
       -1.05245039e-02, -7.00144656e-03, -9.57583785e-02,  2.48182826e-02,
        3.53679135e-02,  2.93628089e-02, -3.08465352e-03, -1.16274385e-02,
       -6.00966159e-03, -1.04608980e-03, -2.90713105e-02, -8.06920510e-03,
        1.66672971e-02, -1.05641827e-01, -5.75915538e-02, -5.59396520e-02,
        5.28114475e-02,  4.72067930e-02,  1.25901610e-01,  7.08308630e-03,
       -5.67950122e-02,  1.45099489e-02,  1.29770711e-01,  1.58195496e-02,
       -2.95390245e-02,  

In [45]:
len(embeddings[0])

384

In [65]:
cos_sim = util.cos_sim(decode, embeddings)


In [66]:
cos_sim

tensor([[0.5119, 0.1782, 0.5119,  ..., 0.1795, 0.1795, 0.1795]])

In [67]:
cos_sim[0][0]

tensor(0.5119)

In [68]:
texts[0]

'Alisha Solid Womens Cycling Shorts'

In [69]:
ret_list=[]

In [70]:
for i in range(len(cos_sim[0])):
    ret_list.append(( cos_sim[0][i], texts[i] ))

In [71]:
ret_list

[(tensor(0.5119), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.1782), 'AW Bellies'),
 (tensor(0.5119), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.1125), 'Sicons All Purpose Arnica Dog Shampoo'),
 (tensor(0.0495),
  'Eternal Gandhi Super Series Crystal Paper Weights  with Silver Finish'),
 (tensor(0.5119), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.2025), 'FabHomeDecor Fabric Double Sofa Bed'),
 (tensor(0.2107), 'dilli bazaaar Bellies Corporate Casuals Casuals'),
 (tensor(0.5119), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.2207), 'Ladela Bellies'),
 (tensor(0.5138), 'Carrel Printed Womens'),
 (tensor(0.0751), 'Sicons All Purpose Tea Tree Dog Shampoo'),
 (tensor(0.5119), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.1110), 'Freelance Vacuum Bottles 350 ml Bottle'),
 (tensor(0.5119), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.2025), 'FabHomeDecor Fabric Double Sofa Bed'),
 (tensor(0.3063), 'Style Foot Bellies'),
 (tensor(0.5138), 'Carrel Printed Womens

In [72]:
all_sentence_combinations = sorted(ret_list, key=lambda x: x[0], reverse=True)


In [73]:
all_sentence_combinations

[(tensor(0.7877), 'People Womens Dress'),
 (tensor(0.7032), 'People Womens Solid Formal Shirt'),
 (tensor(0.6981), 'Sbuys Womens Gathered Dress'),
 (tensor(0.6831), 'People Womens Solid Casual Shirt'),
 (tensor(0.6831), 'People Womens Solid Casual Shirt'),
 (tensor(0.6831), 'People Womens Solid Casual Shirt'),
 (tensor(0.6831), 'People Womens Solid Casual Shirt'),
 (tensor(0.6831), 'People Womens Solid Casual Shirt'),
 (tensor(0.6830), 'People Womens Striped Formal Shirt'),
 (tensor(0.6756), 'People Womens Geometric Print Casual Shirt'),
 (tensor(0.6610), 'G Fashion Striped Cotton Womens Harem Pants'),
 (tensor(0.6594), 'Maya Apparels Womens Gathered Dress'),
 (tensor(0.6532), 'Colors Couture Womens Geometric Print Formal Shirt'),
 (tensor(0.6499), 'Avenster Womens Striped Casual Shirt'),
 (tensor(0.6487), 'Indistar Womens Leggings'),
 (tensor(0.6487), 'Indistar Womens Leggings'),
 (tensor(0.6487), 'Indistar Womens Leggings'),
 (tensor(0.6487), 'Indistar Womens Leggings'),
 (tensor(0.6

In [454]:
query=['maritime shirt']

In [455]:
decode= model.encode(query)

In [456]:
cos_sim = util.cos_sim(decode, embeddings)


In [457]:
cos_sim = util.cos_sim(decode, embeddings)


In [458]:
ret_list=[]

In [459]:
for i in range(len(cos_sim[0])):
    ret_list.append(( cos_sim[0][i], texts[i] ))

In [460]:
ret_list

[(tensor(0.1406), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.2663), 'AW Bellies'),
 (tensor(0.1406), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.0780), 'Sicons All Purpose Arnica Dog Shampoo'),
 (tensor(0.0964),
  'Eternal Gandhi Super Series Crystal Paper Weights  with Silver Finish'),
 (tensor(0.1406), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.1784), 'FabHomeDecor Fabric Double Sofa Bed'),
 (tensor(0.1963), 'dilli bazaaar Bellies Corporate Casuals Casuals'),
 (tensor(0.1406), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.2508), 'Ladela Bellies'),
 (tensor(0.3732), 'Carrel Printed Womens'),
 (tensor(0.0720), 'Sicons All Purpose Tea Tree Dog Shampoo'),
 (tensor(0.1406), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.1154), 'Freelance Vacuum Bottles 350 ml Bottle'),
 (tensor(0.1406), 'Alisha Solid Womens Cycling Shorts'),
 (tensor(0.1784), 'FabHomeDecor Fabric Double Sofa Bed'),
 (tensor(0.2905), 'Style Foot Bellies'),
 (tensor(0.3732), 'Carrel Printed Womens

In [461]:
all_sentence_combinations = sorted(ret_list, key=lambda x: x[0], reverse=True)


In [462]:
all_sentence_combinations

[(tensor(0.6719), 'Ocean 9 Solid Mens Polo T-Shirt'),
 (tensor(0.6719), 'Ocean 9 Solid Mens Polo T-Shirt'),
 (tensor(0.6540), 'Ocean 9 Striped Mens Polo T-Shirt'),
 (tensor(0.6439), 'NavyaRiti Striped Baby Boys Polo Neck T-Shirt'),
 (tensor(0.6439), 'NavyaRiti Striped Baby Boys Polo Neck T-Shirt'),
 (tensor(0.6384), 'Ocean 9 Solid Mens Fashion Neck T-Shirt'),
 (tensor(0.6297), 'Mast & Harbour Womens Printed Casual Shirt'),
 (tensor(0.6267), 'Ocean Race Solid Mens V-neck T-Shirt'),
 (tensor(0.6182), 'Ocean 9 Self Design Mens Fashion Neck T-Shirt'),
 (tensor(0.6182), 'Ocean 9 Self Design Mens Fashion Neck T-Shirt'),
 (tensor(0.6143), 'Well on Embroidered Mens Polo Neck T-Shirt'),
 (tensor(0.5910), 'Okane Solid Mens Polo T-Shirt'),
 (tensor(0.5910), 'Okane Solid Mens Polo T-Shirt'),
 (tensor(0.5910), 'Okane Solid Mens Polo T-Shirt'),
 (tensor(0.5895), 'Ocean Race Solid Mens Round Neck T-Shirt'),
 (tensor(0.5895), 'Ocean Race Solid Mens Round Neck T-Shirt'),
 (tensor(0.5895), 'Ocean Race S

In [453]:
all_sentence_combinations[0][1]

'IaD Organic Compost Soil Manure'

In [349]:
from sklearn.cluster import KMeans
import numpy as np


In [204]:
embedder = SentenceTransformer('all-MiniLM-L6-v2')

# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]
corpus_embeddings = embedder.encode(corpus)



In [205]:
corpus_embeddings

array([[ 0.03324158,  0.00440608, -0.00627695, ...,  0.06917302,
        -0.02458484, -0.03756437],
       [ 0.05251841,  0.05524129, -0.01118819, ..., -0.01619392,
        -0.06022898, -0.04115055],
       [-0.00858899,  0.01801802,  0.05754676, ...,  0.06797203,
         0.00763671, -0.03118757],
       ...,
       [ 0.05438589,  0.05397908, -0.00367976, ...,  0.03249276,
         0.02187711,  0.06213459],
       [-0.00162549,  0.04804117,  0.01033579, ..., -0.00226647,
         0.0930332 ,  0.03106403],
       [ 0.03091298,  0.00874069, -0.0602878 , ...,  0.04663471,
         0.03548015, -0.00794347]], dtype=float32)

In [206]:
corpus_embeddings = corpus_embeddings /  np.linalg.norm(corpus_embeddings, axis=1, keepdims=True)


In [207]:
corpus_embeddings

array([[ 0.03324158,  0.00440608, -0.00627695, ...,  0.06917302,
        -0.02458484, -0.03756437],
       [ 0.05251841,  0.05524129, -0.01118819, ..., -0.01619392,
        -0.06022899, -0.04115056],
       [-0.00858899,  0.01801802,  0.05754676, ...,  0.06797203,
         0.00763671, -0.03118757],
       ...,
       [ 0.05438589,  0.05397908, -0.00367976, ...,  0.03249276,
         0.02187711,  0.06213459],
       [-0.00162549,  0.04804117,  0.01033579, ..., -0.00226647,
         0.0930332 ,  0.03106403],
       [ 0.03091298,  0.00874069, -0.06028781, ...,  0.04663472,
         0.03548015, -0.00794347]], dtype=float32)

In [208]:
corpus_embeddings[0]


array([ 3.32415812e-02,  4.40608338e-03, -6.27695443e-03,  4.83787283e-02,
       -1.38702288e-01, -3.36174071e-02,  1.01128340e-01, -5.43849505e-02,
       -4.32478040e-02, -3.99411432e-02,  7.78634241e-03, -1.27489232e-02,
       -6.68302253e-02, -1.73865855e-02,  4.74506281e-02, -5.77242561e-02,
        1.01888403e-01, -9.11653333e-04,  8.22615027e-02, -5.03415652e-02,
        6.77303150e-02,  4.08765376e-02, -3.58018912e-02, -1.00682445e-01,
       -6.69354945e-03, -5.31686097e-02,  1.00335158e-01, -5.46136275e-02,
       -2.28481535e-02,  1.38387363e-02,  7.48658404e-02, -6.17880151e-02,
        6.39215708e-02,  1.62387397e-02, -5.32299392e-02, -3.86083946e-02,
        3.15276124e-02, -8.11530054e-02, -3.31432298e-02, -5.38510620e-04,
       -3.96069000e-03, -1.52734173e-02, -9.86416941e-04,  9.57988054e-02,
       -5.42920232e-02,  1.84572097e-02, -1.07143573e-01,  1.38884569e-02,
        3.94072384e-02, -2.69243792e-02, -9.15988982e-02, -1.14195254e-02,
        3.38137150e-02, -

In [202]:

len(corpus_embeddings)

15

In [203]:
len(corpus_embeddings[0])

384

In [209]:
clustering_model = KMeans(n_clusters=4)


In [210]:
clustering_model.fit(corpus_embeddings)


KMeans(n_clusters=4)

In [211]:
cluster_assignment = clustering_model.labels_


In [212]:
print(cluster_assignment)


[0 0 2 0 0 1 1 2 2 3 3 2 2 2 2]


In [213]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences


{0: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 2: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.',
  'man and women with their baby are watching cheetah in zoo'],
 1: ['The girl is carrying a baby.', 'The baby is carried by the woman'],
 3: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.']}

In [ ]:
corpus_embeddings = embedder.encode(corpus)


In [217]:
len(embeddings)

19979

In [225]:
clustering_model = KMeans(n_clusters=500)


In [226]:
clustering_model.fit(embeddings)


KMeans(n_clusters=500)

In [227]:
cluster_assignment = clustering_model.labels_


In [228]:
print(cluster_assignment)


[143 320 143 ... 333 333 333]


In [229]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(texts[sentence_id])
clustered_sentences

{143: ['Alisha Solid Womens Cycling Shorts',
  'Alisha Solid Womens Cycling Shorts',
  'Alisha Solid Womens Cycling Shorts',
  'Alisha Solid Womens Cycling Shorts',
  'Alisha Solid Womens Cycling Shorts',
  'Alisha Solid Womens Cycling Shorts',
  'Alisha Solid Womens Cycling Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Shorts Gym Shorts Swim Shorts',
  'Mynte Solid Womens Cycling Sho